### PR TITLE
Correct character encoding issues for dict.csv

### PR DESCRIPTION
**Pull request by marcreichman-pfi**
Between initial and second commits of dict.csv, backslashed character escape codes were interpreted but were somehow corrupted on the way. I took the original file, diffed back in the original sequences and re-interpreted them via bash and printf "%b" to create a correctly-interpreted file.

Conversation reference: https://github.com/openimages/dataset/commit/9e794daaa1b3ad3e45aefd78832c4fbb4a65edf7#commitcomment-22124560

(PR Reopened from correct account)

### CODE REVIEW

**Comment by marcreichman-pfi** [comment]
OK, I'm somewhat sure this is from the correct account now. My CLA is for "Pixel Forensics, Inc." (my company).

**Comment by rkrasin** [comment]
Thank you, Marc!

@vfgomes Victor, can you please take a look? The change itself looks good to me and I recommend to merge it, but there seem to be a manual step required for checking the corporate SLA. Thank you!

**Comment by marcreichman-pfi** [comment]
Still haven't seen anything here. Is there something else I need to provide?

**Comment by krasin** [comment]
@marcreichman-pfi thank you for pinging the bot. Apparently, something was slow on its side and it didn't catch it then.

@vfgomes it's good to merge, I think

**Comment by krasin** [comment]
Thank you, Victor!

**Pull request merged**
