### PR TITLE
Correct character encoding issues for dict.csv

### PR DESCRIPTION
**Pull request by marcreichman**
Between initial and second commits of dict.csv, backslashed character escape codes were interpreted but were somehow corrupted on the way. I took the original file, diffed back in the original sequences and re-interpreted them via bash and `printf "%b"` to create a correctly-interpreted file.

Conversation reference: https://github.com/openimages/dataset/commit/9e794daaa1b3ad3e45aefd78832c4fbb4a65edf7#commitcomment-22124560

### CODE REVIEW

**Comment by rkrasin** [comment]
The changes look good to me. Ideally, these commits should be squashed into one (so that there's no back-in-forth in the history), but github does not make it easy, so I would not insist.

Once the cla/google bot is happy, I will try get the attention of the current maintainers.

**Comment by marcreichman** [comment]
OK, in theory it's signed. Have a good weekend!

**Comment by rkrasin** [comment]
@marcreichman the bot still does not want to become green. Did you sign it under the same email as the commits were made (marcreichman-pfi)

**Comment by 4F2E4A2E** [comment]
@marcreichman please sign again

**Comment by marcreichman** [comment]
I believe I had some mixed up personal and work github accounts. I signed the CLA under the same e-mail as the committer, but this PR was opened by my personal account by accident. I'm going to close this and re-open from the marcreichman-pfi and everything should be all set.

**Pull request closed without merging**
